# -*- coding: utf-8 -*-
"""Python_task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zT8kUCAZ0Se3PXVGrrB_i6P8EtONkGxB

Необходимо разработать консольное приложение для управления библиотекой книг.

Приложение должно позволять добавлять, удалять, искать и отображать книги.

Каждая книга должна содержать следующие поля:

 • id (уникальный идентификатор, генерируется автоматически)

 • title (название книги)

 • author (автор книги)

 • year (год издания)

 • status (статус книги: “в наличии”, “выдана”)

Требования

 1 Добавление книги: Пользователь вводит title, author и year, после чего книга добавляется в библиотеку с уникальным id и статусом “в наличии”.

 2 Удаление книги: Пользователь вводит id книги, которую нужно удалить.

 3 Поиск книги: Пользователь может искать книги по title, author или year.

 4 Отображение всех книг: Приложение выводит список всех книг с их id, title, author, year и status.

 5 Изменение статуса книги: Пользователь вводит id книги и новый статус (“в наличии” или “выдана”).

 Дополнительные требования

 • Реализовать хранение данных в текстовом или json формате.

 • Обеспечить корректную обработку ошибок (например, попытка удалить несуществующую книгу).

 • Написать функции для каждой операции (добавление, удаление, поиск, отображение, изменение статуса).

 • Не использовать сторонние библиотеки.
"""

import json

def load_data(data_file):
    try:
        with open(data_file, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        return []

def save_data(data, data_file):
    with open(data_file, 'w') as f:
        json.dump(data, f, indent=4)
    return data

class Book:
    _id_counter = 1
    def __init__(self, title, author, year, status="в наличии"):
        self.id = Book._id_counter
        Book._id_counter += 1
        self.title = normalize_string(title)
        self.author = normalize_string(author)
        self.year = year
        self.status = status

    def __str__(self):
        return f"Book {self.id}: {self.title} by {self.author}, {self.year} ({self.status})"

    def set_status(self, status):
        if status in ["в наличии", "выдана"]:
            self.status = status
        else:
            raise ValueError("Invalid status")

    def get_status(self):
        return self.status

class Library:
    def __init__(self, library_file=None):
        if library_file:
            self.data = load_data(library_file)
        else:
            self.data = load_data('library_file.json')

    def add_book(self, book):

        if not self.search_book(book.title,book.author,None):
          self.data.append(book.__dict__)
          save_data(self.data, 'library_file.json')
          print(f'Книга "{book.title}" добавлена в библиотеку.')
        else:
          print("Такая книгу уже существует")

    def delete_book(self, book_id):
      results = self.search_book(None,None,(book_id))
      print(results)
      if results:
            for book in results:
                self.data.remove(book)
                save_data(self.data, 'library_file.json')
                print(f'Книга с id {book_id} удалена.')
            return
      else:
        print(f'Книга с id {book_id} не найдена.')

    def view_book(self, book_id):
        results = self.search_book(None,None,(book_id))
        if results:
            for book in results:
                print(f"ID: {book['id']}, Title: {book['title']}, Author: {book['author']}, Year: {book['year']}, Status: {book['status']}")
        else:
            print(f'Книга с id {book_id} не найдена.')

    def view_all_books(self):
        for book in self.data:
            print(f"ID: {book['id']}, Title: {book['title']}, Author: {book['author']}, Year: {book['year']}, Status: {book['status']}")

    def change_status(self, book_id, status):
      results = self.search_book(None,None,(book_id))
      if results:
            for book in results:
                book['status']= status
                print(f'Статус книги с id {book_id} изменен на {status}')
            save_data(self.data, 'library_file.json')
            return
      else:
        print(f'Книга с id {book_id} не найдена.')

    def search_book(self,title,author,book_id):
        results = []
        for book in self.data:
            if title and normalize_string(title) in book['title'] or author and normalize_string(author) in book['author'] or book_id and book_id ==book['id']:
                results.append(book)
        return results


def print_menu():
  print('Меню:')
  print('1. Добавить книгу')
  print('2. Удалить книгу')
  print('3. Поиск книги')
  print('4. Отобразить все книги')
  print('5. Изменить статус книги')
  print('6. Выход')

def normalize_string(s):
    s = ' '.join(s.split())
    s = ''.join(c for c in s if c.isalnum() or c.isspace())
    s = s.lower()
    return s

def main():
  library_1=Library()
  while True:
      print_menu()
      choice = input('Выберите пункт меню: ')
      if choice == '1':
            title = input('Введите название книги: ')
            author = input('Введите автора книги: ')
            year = input('Введите год издания книги: ')
            if not year.isdigit():
              print("Ошибка ввода")
            else:
              book=Book(title, author, year)
              library_1.add_book(book)
      elif choice == '2':
            book_id = input('Введите id книги для удаления: ')
            if not book_id.isdigit():
              print("Ошибка ввода")
            else:
              book_id =int(book_id)
              library_1.delete_book(book_id)
      elif choice == '3':
            title = input('Введите название книги: ')
            author = input('Введите автора книги: ')
            book_id = input('Введите id книги: ')

            if book_id and not book_id.isdigit():
              print("Ошибка ввода")
            else:
              results =  library_1.search_book(title,author,book_id)
              if results:
                for book in results:
                    print(f"ID: {book['id']}, Title: {book['title']}, Author: {book['author']}, Year: {book['year']}, Status: {book['status']}")
              else:
                print('Книга не найдена.')
      elif choice == '4':
             library_1.view_all_books()
      elif choice == '5':
            book_id = input('Введите id книги для изменения статуса: ')
            if not book_id.isdigit():
              print("Ошибка ввода")
            else:
              book_id =int(book_id)
              status= input('Введите status книги для изменения статуса: ')
              library_1.change_status(book_id,status )
      elif choice == '6':
            break
      else:
            print('Неверный выбор. Попробуйте снова.')

if __name__ == '__main__':
    main()

import json

def load_data(data_file: str) -> list:
    """
    Loads data from a JSON file.

    Args:
        data_file (str): The file path to load data from.

    Returns:
        list: The loaded data.
    """
    try:
        with open(data_file, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        return []

def save_data(data: list, data_file: str) -> list:
    """
    Saves data to a JSON file.

    Args:
        data (list): The data to save.
        data_file (str): The file path to save data to.

    Returns:
        list: The saved data.
    """
    with open(data_file, 'w') as f:
        json.dump(data, f, indent=4)
    return data

class Book:
    """
    Represents a book object.
    """
    _id_counter: int = 1

    def __init__(self, title: str, author: str, year: int, status: str = "в наличии"):
        """
        Initializes a book object.

        Args:
            title (str): The book title.
            author (str): The book author.
            year (int): The book year.
            status (str): The book status.
        """
        self.id: int = Book._id_counter
        Book._id_counter += 1
        self.title: str = normalize_string(title)
        self.author: str = normalize_string(author)
        self.year: int = year
        self.status: str = status

    def __str__(self) -> str:
        """
        Returns a string representation of the book.
        """
        return f"Book {self.id}: {self.title} by {self.author}, {self.year} ({self.status})"

    def set_status(self, status: str) -> None:
        """
        Sets the book status.

        Args:
            status (str): The new book status.
        """
        if status in ["в наличии", "выдана"]:
            self.status = status
        else:
            raise ValueError("Invalid status")

    def get_status(self) -> str:
        """
        Returns the book status.
        """
        return self.status

class Library:
    """
    Represents a library object.
    """
    def __init__(self, library_file: str = None):
        """
        Initializes a library object.

        Args:
            library_file (str): The file path to load data from.
        """
        if library_file:
            self.data: list = load_data(library_file)
        else:
            self.data: list = load_data('library_file.json')

    def change_status(self, book_id: int, status: str) -> None:
        """
        Changes the status of a book.

        Args:
            book_id (int): The book ID to change status.
            status (str): The new book status.
        """
        results = self.search_book(None, None, (book_id))
        if results:
            for book in results:
                book['status'] = status
                print(f'Статус книги с id {book_id} изменен на {status}')
            save_data(self.data, 'library_file.json')
            return
        else:
            print(f'Книга с id {book_id} не найдена.')

    def search_book(self, title: str, author: str, book_id: int) -> list:
        """
        Searches for a book in the library.

        Args:
            title (str): The book title to search.
            author (str): The book author to search.
            book_id (int): The book ID to search.

        Returns:
            list: The search results.
        """
        results = []
        for book in self.data:
            if title and normalize_string(title) in book['title'] or author and normalize_string(author) in book['author'] or book_id and book_id == book['id']:
                results.append(book)
        return results


def print_menu() -> None:
    """
    Prints the menu options.
    """
    print('Меню:')
    print('1. Добавить книгу')
    print('2. Удалить книгу')
    print('3. Поиск книги')
    print('4. Отобразить все книги')
    print('5. Изменить статус книги')
    print('6. Выход')


def normalize_string(s: str) -> str:
    """
    Normalizes a string by removing extra spaces and converting to lowercase.

    Args:
        s (str): The string to normalize.

    Returns:
        str: The normalized string.
    """
    s = '.join(s.split())
    s = ''.join(c for c in s if c.isalnum() or c.isspace())
    s = s.lower()
    return s


def main() -> None:
    """
    The main function of the program.
    """
    library_1 = Library()
    while True:
        print_menu()
        choice = input('Выберите пункт меню: ')
        if choice == '1':
            title = input('Введите название книги: ')
            author = input('Введите автора книги: ')
            year = input('Введите год издания книги: ')
            if not year.isdigit():
                print("Ошибка ввода")
            else:
                book = Book(title, author, year)
                library_1.add_book(book)
        elif choice == '2':
            book_id = input('Введите id книги для удаления: ')
            if not book_id.isdigit():
                print("Ошибка ввода")
            else:
                book_id = int(book_id)
                library_1.delete_book(book_id)
        elif choice == '3':
            title = input('Введите название книги: ')
            author = input('Введите автора книги: ')
            book_id = input('Введите id книги: ')
            if book_id and not book_id.isdigit():
                print("Ошибка ввода")
            else:
                results = library_1.search_book(title, author, book_id)
                if results:
                    for book in results:
                        print(f"ID: {book['id']}, Title: {book['title']}, Author: {book['author']}, Year: {book['year']}, Status: {book['status']}")
                else:
                    print('Книга не найдена.')
        elif choice == '4':
            library_1.view_all_books()
        elif choice == '5':
            book_id = input('Введите id книги для изменения статуса: ')
            if not book_id.isdigit():
                print("Ошибка ввода")
            else:
                book_id = int(book_id)
                status = input('Введите status книги для изменения статуса: ')
                library_1.change_status(book_id, status)
        elif choice == '6':
            break
        else:
            print('Неверный выбор. Попробуйте снова.')

if __name__ == '__main__':
    main()

import unittest



class TestLibrary(unittest.TestCase):
    def setUp(self):

        self.library = Library("test.json")

    def test_add_book(self):

        book = Book("Test Book", "Test Author", 2022)
        self.library.add_book(book)
        self.assertIn(book.__dict__, self.library.data)

    def test_delete_book(self):
        book = Book("Test Book", "Test Author", 2022)
        self.library.add_book(book)
        self.library.delete_book(book.id)
        self.assertNotIn(book.__dict__, self.library.data)


    def test_change_status(self):
        book = Book("Test Book", "Test Author", 2022)
        self.library.add_book(book)
        self.library.change_status(book.id, "выдана")
        self.assertEqual(book.status, "выдана")

    def test_search_book(self):
        book1 = Book("Test Book 20", "Test Author 1", 2022)
        self.library.add_book(book1)
        results = self.library.search_book("Test Book 1","Test Author 1",None)
        self.assertIn(book1.__dict__, results)

    def test_search_book_1(self):
        book1 = Book("Test Book 1", "Test Author 1", 2022)
        self.library.add_book(book1)
        results = self.library.search_book("Test Book 1","Test Author 1",None)
        self.assertIn(book1.__dict__, results)


if __name__ == '__main__':

  s = unittest.TestLoader().loadTestsFromTestCase(TestLibrary)
  unittest.TextTestRunner().run(s)